# Generated by Django 2.1.1 on 2018-09-19 06:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('employees', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('pattern', models.TextField(null=True)),
                ('sources', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HunterItemBaba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(null=True)),
                ('emails', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('html', models.TextField(null=True)),
                ('timestamp', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceItemBaba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
