# Generated by Django 2.1.1 on 2018-09-19 09:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0002_companyitembaba'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyItemNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('employees', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HunterItemNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('pattern', models.TextField(null=True)),
                ('sources', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceItemNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(null=True)),
                ('emails', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('links', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('html', models.TextField(null=True)),
            ],
        ),
    ]
